name: 'kubectl-jobs'
description: 'Triggers a deployment of a kubernetes job and checks for completion of the job. Then removes the job resources.'
inputs:
  job-name:
    description: 'Name of the job to deploy.'
    required: true
  namespace:
    description: 'Namespace to deploy the job to.'
    required: true
  sleep-time:
    description: 'Time to sleep between checking for job completion.'
    required: true
    default: '5s'
  log-follow-duration:
    description: 'Duration to follow the logs of the job.'
    required: true
    default: '60s'
  KUBE_CONFIG_DATA:
    description: 'Kubeconfig data to use for kubectl commands.'
    required: true
    default: ''
  job-filepath:
    description: 'Filepath to the job yaml file to deploy.'
    required: true
    default: ''
  command:
    description: 'Command to run with kubectl or helm.'
    default: ''
outputs:
  result:
    description: "Output returned by your Helm or kubectl command"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.job-name }}
    - ${{ inputs.namespace }}
    - ${{ inputs.sleep-time }}
    - ${{ inputs.log-follow-duration }}
    - ${{ inputs.KUBE_CONFIG_DATA }}
    - ${{ inputs.job-filepath }}
    - ${{ inputs.command }}
